### ISSUE TITLE
Error with schema creation

### ISSUE THREAD

**Issue by Sogl** [Multicolour/multicolour#48] opened 2016-02-18 13:32 UTC
Hi!

I'm trying to change cli example app to my needs.

Some problems:
1. I use `migrate: 'drop'` in defaults adapter section to re-create my tables on each run. More info:
http://sailsjs.org/documentation/concepts/models-and-orm/model-settings#?migrate

Today I found that my PostgreSQL tables not created at all (zero tables in empty DB), but app starts without any error. Maybe I need debug option or something? Is `migrate` option enough to create tables?
2. I tried to solve my 1st problem with `multicolour-seed` module, but app can't start:
```
sogl:tw artyom$ NODE_ENV=development node app.js
- Seeding the database with fake data.
/Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:467
        Object.keys(collection.schema).forEach(function(schemaKey) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at __CREATE__ (/Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:467:16)
    at after (/Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:1292:7)
    at /Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:1181:7
    at /Users/artyom/projects/tw/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:82:9
    at dispense (/Users/artyom/projects/tw/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:250:16)
    at Object.me.acquire (/Users/artyom/projects/tw/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:319:5)
    at Object.pool.connect (/Users/artyom/projects/tw/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:76:12)
    at PG.connect (/Users/artyom/projects/tw/node_modules/sails-postgresql/node_modules/pg/lib/index.js:49:8)
    at spawnConnection (/Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:1180:8)
    at Object.module.exports.adapter.create (/Users/artyom/projects/tw/node_modules/sails-postgresql/lib/adapter.js:436:7)
    at module.exports.create (/Users/artyom/projects/tw/node_modules/waterline/lib/waterline/adapter/dql.js:84:13)
    at createValues (/Users/artyom/projects/tw/node_modules/waterline/lib/waterline/query/dql/create.js:214:16)
    at /Users/artyom/projects/tw/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at /Users/artyom/projects/tw/node_modules/async/lib/async.js:708:13
    at /Users/artyom/projects/tw/node_modules/async/lib/async.js:49:16
sogl:tw artyom$
```

My repo here:
https://github.com/Sogl/multicolour-tw

**Comment by davemackintosh** [comment] 2016-03-03 11:37
@Sogl: Confirmed, will address tomorrow.

**Comment by Sogl** [comment] 2016-04-15 04:34
@davemackintosh Found something?

**Comment by davemackintosh** [comment] 2016-04-19 08:13
Hey @Sogl, apologies. I've been really really ill and really busy with client work. Unfortunately, I don't have any support to keep this going while I'm ill. I'll be back on Multicolour in a week or so to push for the `0.4.0` release which includes a fix for whatever is causing this.

**Comment by davemackintosh** [comment] 2016-04-20 17:25
Okay, so there's no official support for a global `migrate` options. It has to be done on a model by model basis. That said, this issue still occurs and is in fact an issue with the seed module not picking up the `columnName` property in your `user` object.

I'm going to close this issue and open one on the appropriate repo.

**Comment by davemackintosh** [comment] 2016-04-20 19:09
Okay, it is to do with core. It is because the `multicolour_user` model has no migration policy. I will have a think about possible solutions to this as I don't want to make "possible data loss" the default setting.

**Comment by Sogl** [comment] 2016-04-22 10:18
>Okay, so there's no official support for a global migrate options. It has to be done on a model by model basis. 

Really? I saw info about it from one of sails waterline contributors.

**Comment by davemackintosh** [comment] 2016-04-29 14:20
@Sogl Nothing in the docs and no matter what I set the value to it doesn't take any affect.

**Comment by davemackintosh** [comment] 2016-06-02 14:09
@Sogl A fix will be going in very soon as part of the 0.4.0 release.

**Comment by davemackintosh** [comment] 2016-07-15 10:14
This is resolved in the latest version.

![image](https://cloud.githubusercontent.com/assets/1430657/16871173/4f6ef25e-4a7d-11e6-8ffe-9bec347746e0.png)

```json
{
  "version": "1.0.0",
  "scripts": {
    "start": "node app.js"
  },
  "engineStrict": true,
  "engines": {
    "node": ">= 4.0.0"
  },
  "dependencies": {
    "multicolour": "^0.3.5",
    "multicolour-auth-oauth": "^1.1.11",
    "multicolour-hapi-jsonapi": "^0.2.21",
    "multicolour-seed": "0.0.6",
    "multicolour-server-hapi": "^1.3.2",
    "sails-postgresql": "^0.11.4"
  },
  "name": "tw"
}
```

**Closed by davemackintosh** 2016-07-15 10:14 UTC
Labels: bug, in progress, investigate, P1
